spring.application.name=customer-service

spring.datasource.url=jdbc:postgresql://postgres-db:5432/order_management?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata'
spring.sql.init.mode=always
server.port=8081